job/urls.py
from django.urls import path
from job import views
from job import serializerviews
from .serializerviews import JobPostCreateListView, CarouselView, JobPostsByCategoryAPIView


app_name = 'job'

urlpatterns = [
    #    user authentication
    path("register/", views.Register, name="register"),
    path("login/", views.Login, name="login"),
    path("logout/", views.Logout, name="logout"),
    path('index', views.index, name='index'),
    path('', views.dashboard, name='dashboard'), 
    
    #------------------------New URLS----------------------------------#
    path('approve-job-list', views.approved_job_list, name='approve-job-list'),
    path('create_videsh_job', views.create_job_post, name='create_videsh_job'),
    path('videsh_job_list/', views.videsh_job_list, name='videsh_job_list'),
    path('videsh_job/<int:pk>/', views.videsh_job_detail, name='job_detail'),
    path('videsh_job/update/<int:pk>/', views.update_videsh_job_post, name='update_videsh_job_post'),
    path('client_interview', views.client_interview_posts, name='client_interview'),
    path('delete_videsh_job_post/<int:pk>/', views.delete_videsh_job_post, name='delete_videsh_job_post'),
    path('telephonic_interview', views.telephonic_interview_posts, name='telephonic_interview'),
    path('licence_holder', views.licence_holder_posts, name='licence_holder'),
    path('cv_selection', views.cv_selection_posts, name='cv_selection'),
    path('job/create/', views.create_normal_job_post, name='create_normal_job_post'),
    path('normal_job_list', views.normal_job_list, name='normal_job_list'),
    path('job/<int:pk>/', views.normal_job_detail, name='normal_job_detail'),
    path('update_normal_job_post/<int:pk>/', views.update_normal_job_post, name='update_normal_job_post'),
    path('delete_normal_job_post/<int:pk>/', views.delete_normal_job_post, name='delete_normal_job_post'),
    path('show_hospital_jobs', views.show_hospital_jobs, name='show_hospital_jobs'),
    path('create_normal_job_post', views.create_normal_job_post, name='create_normal_job_post'),
    path('sliders', views.show_carousel_slider, name='sliders'),
    path('add_sliders', views.CarouselSliderCreateView.as_view(), name='add_sliders'),
    path('slider_update/<int:pk>/', views.CarouselSliderUpdate.as_view(), name='slider_update'),
    path('slider_delete/<int:pk>/', views.CarouselSliderDelete.as_view(), name='slider_delete'),
    
    path('ad_photo_list', views.ClientAdPhotosList.as_view(), name='ad_photo_list'),
    path('ad_photos_create/', views.ClientAdPhotosCreate.as_view(), name='ad_photos_create'),
    path('ad_photos_update/<int:pk>/', views.ClientAdPhotosUpdate.as_view(), name='ad_photos_update'),
    path('ad_photos_delete/<int:pk>/', views.ClientAdPhotosDelete.as_view(), name='ad_photos_delete'),
    path('terms_and_conditions', views.TermsAndConditionsListView.as_view(), name='terms_and_conditions'),
    path('terms_and_conditions_create', views.TermsAndConditionsCreateView.as_view(), name='terms_and_conditions_create'),
    path('terms_and_conditions_update/<int:pk>/', views.TermsAndConditionsUpdateView.as_view(), name='terms_and_conditions_update'),
    path('terms_and_conditions_delete/<int:pk>/', views.TermsAndConditionsDeleteView.as_view(), name='terms_and_conditions_delete'),
    path('privacy-policy', views.privacy_policy, name='privacy-policy'),


    #===================APIS URLS==================
    path('api/job-categories/', serializerviews.JobCategoryListCreateView.as_view(), name='job-category-list'),
    path('api/job-posts-by-category/<int:category_id>/', JobPostsByCategoryAPIView.as_view(), name='job-posts-by-category'),
    path('api/job-list', JobPostCreateListView.as_view()),
    path('<int:id>', JobPostCreateListView.as_view()),
    path('api/carousel-slider', CarouselView.as_view(), name='api/carousel-slider'),
    # path('api/category/', serializerviews.show_school_jobs)
    path('api/create_job_post/', serializerviews.create_job_post, name='api_create_job_post'),
    path('api/videsh_job_list', serializerviews.videsh_job_list),
    path('api/client-interview/', serializerviews.ClientInterviewJobPostList.as_view(), name='client-interview-job-list'),
    path('api/cv-selection/', serializerviews.CVSelectionJobPostList.as_view(), name='cv-selection-job-list'),
    path('api/telephonic-interview/', serializerviews.TelephonicInterviewJobPostList.as_view(), name='telephonic-interview-job-list'),
    path('api/license-holder/', serializerviews.LicenseHolderJobPostList.as_view(), name='license-holder-job-list'),
    path('api/normal-job-posts/', serializerviews.normal_job_post_list, name='normal-job-post-list'),
    path('api/normal-job-posts/<int:pk>/', serializerviews.normal_job_post_detail, name='normal-job-post-detail'),
    path('api/desh_me_job/', serializerviews.DeshMeJobPostList.as_view(), name='desh-me-job-list'),
    path('api/hospital_me_job/', serializerviews.HosptialMeJobPostList.as_view(), name='hospital-me-job-list'),
    path('api/carousel/', serializerviews.CarouselSliderList.as_view(), name='carousel'),
    path('api/adphotos/', serializerviews.ClientAdPhotosList.as_view(), name='adphotos'),
    path('api/terms', serializerviews.TermsAndConditionsList.as_view(), name='terms'),
    
]   


































    # path('job/create/', views.create_job_post, name='create_job_post'),
    # path('create_job_post', views.CreateJobPost.as_view(), name='create_job_post'),
    # path('job_post/<int:pk>/update/', views.JobPostUpdateView.as_view(), name='job_post_update'),
    
    # path('job-list', views.job_list, name='job-list'), 
    # 
    # path('delete_post/<int:id>/', views.delete_job_post, name='delete_post'), 
    # path('category-list', views.show_job_categories, name='category-list'),
    # path('create_job_category', views.JobCategoryCreateView.as_view(), name='create_job_category'),
    # path('category/<int:pk>/update/', views.JobCategoryUpdateView.as_view(), name='category_update'),
    # path('sliders', views.show_carousel_slider, name='sliders'),
    # path('add_sliders', views.CarouselSliderCreateView.as_view(), name='add_sliders'),
    # # path('videsh-job', views.show_videsh_job, name='videsh-job'),
    # # path('desh-job', views.show_desh_job, name='desh-job'),
    # # path('school-job', views.show_school_job, name='school-job'),
    # # path('hospital-job', views.show_hospital_job, name='hospital-job'),
    # # path('resturant-job', views.show_resturant_job, name='resturant-job'),
    # # path('medical-job', views.show_medical_store, name='medical-job'),

    # # path('jobs/<int:job_category_id>/', views.show_videsh_job, name='jobs-by-category'),

job_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from job_app import settings

urlpatterns = [
    path('suadmin/', admin.site.urls),
    path('', include('job.urls', namespace='job'),),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL,
                                                                                         document_root=settings.STATIC_ROOT)

job/views.py
from django.shortcuts import render
from .models import JobPost, VideshJobPost, NormalJobPost, CarouselSlider, ClientAdPhotos, Terms_and_conditions
from .forms import NormalJobPostForm, AddSliderForm, CarouselSliderForm, ClientAdPhotosForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth  import authenticate,  login, logout
from django.views.generic import CreateView, ListView,UpdateView, DeleteView
from django.urls import reverse_lazy
from django.urls import reverse

# Create your views here.

def Register(request):
    if request.method=="POST":   
        username = request.POST['username']
        email = request.POST['email']
        first_name=request.POST['first_name']
        last_name=request.POST['last_name']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        
        if password1 != password2:
            messages.error(request, "Passwords do not match.")
            return redirect('/register')
        
        user = User.objects.create_user(username, email, password1)
        user.first_name = first_name
        user.last_name = last_name
        user.save()
        return render(request, 'login.html')   
    return render(request, "job/accounts/register.html")



def Login(request):
    if request.method=="POST":
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(username=username, password=password)
        
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect("job:dashboard")
        else:
            messages.error(request, "Invalid Credentials")
        return render(request, "job/accounts/login.html")
        # return render(request, 'blog.html')   
    return render(request, "job/accounts/login.html")


def Logout(request):
    logout(request)
    messages.success(request, "Successfully logged out")
    return redirect('/login')



@login_required(login_url = '/login')
def dashboard(request):
    normal_job_posts = NormalJobPost.objects.all()
    videsh_job_posts = VideshJobPost.objects.all()
    
    # Combine data from both models into a single list
    job_lists = list(normal_job_posts) + list(videsh_job_posts)
    return render(request, "job/dashboard.html", {'job_lists': job_lists})


def index(request):
    return render(request, "job/base.html")



@login_required(login_url = '/login')
def approved_job_list(request):
    approved_job_lists = JobPost.objects.filter(is_approved=True)
    return render(request, 'job/approved_job_list.html', {
        'approved_job_lists': approved_job_lists,
    })


#=======================================================================================





from django.shortcuts import render, get_object_or_404
from .models import VideshJobPost

from .forms import VideshJobPostForm

def create_job_post(request):
    if request.method == 'POST':
        form = VideshJobPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('job:videsh_job_list')  # Redirect to the job list page after creating a post
    else:
        form = VideshJobPostForm()
    return render(request, 'job/create_videsh_job_post.html', {'form': form})



def videsh_job_list(request):
    videsh_job_posts = VideshJobPost.objects.all()
    return render(request, 'job/videsh_job_list.html', {'videsh_job_posts': videsh_job_posts})

def videsh_job_detail(request, pk):
    videsh_job_posts = get_object_or_404(VideshJobPost, pk=pk)
    return render(request, 'job_detail.html', {'videsh_job_posts': videsh_job_posts})


def update_videsh_job_post(request, pk):
    videsh_job_post = get_object_or_404(VideshJobPost, pk=pk)

    if request.method == 'POST':
        form = VideshJobPostForm(request.POST, request.FILES, instance=videsh_job_post)
        if form.is_valid():
            form.save()
            return redirect('job:videsh_job_list')  # Redirect to the job list page after updating the post
    else:
        form = VideshJobPostForm(instance=videsh_job_post)
    return render(request, 'job/update_videsh_job_post.html', {'form': form})

def delete_videsh_job_post(request, pk):
    videsh_job_post = get_object_or_404(VideshJobPost, pk=pk)
    if request.method == 'POST':
        videsh_job_post.delete()
    return redirect('job:normal_job_list')




def client_interview_posts(request):
    job_posts = VideshJobPost.objects.filter(job_category='CI')
    return render(request, 'job/client_interview_posts.html', {'job_posts': job_posts})

def telephonic_interview_posts(request):
    job_posts = VideshJobPost.objects.filter(job_category='TI')
    return render(request, 'job/telephonic_interview_posts.html', {'job_posts': job_posts})


def licence_holder_posts(request):
    job_posts = VideshJobPost.objects.filter(job_category='LH')
    return render(request, 'job/license_holder_posts.html', {'job_posts': job_posts})


def cv_selection_posts(request):
    job_posts = VideshJobPost.objects.filter(job_category='CS')
    return render(request, 'job/cv_selection_posts.html', {'job_posts': job_posts})


def create_normal_job_post(request):
    if request.method == 'POST':
        form = NormalJobPostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('job:normal_job_list')  # Redirect to the job list page after creating a post
    else:
        form = NormalJobPostForm()
    return render(request, 'job/create_normal_job_post.html', {'form': form})


def normal_job_list(request):
    normal_job_posts = NormalJobPost.objects.all()
    return render(request, 'job/normal_job_list.html', {'normal_job_posts': normal_job_posts})

def normal_job_detail(request, pk):
    normal_job_post = get_object_or_404(NormalJobPost, pk=pk)
    return render(request, 'normal_job_detail.html', {'normal_job_post': normal_job_post})



def update_normal_job_post(request, pk):
    normal_job_post = get_object_or_404(NormalJobPost, pk=pk)
    if request.method == 'POST':
        form = NormalJobPostForm(request.POST, request.FILES, instance=normal_job_post)
        if form.is_valid():
            form.save()
            return redirect('job:normal_job_list')  # Redirect to the job list page after updating the post
    else:
        form = NormalJobPostForm(instance=normal_job_post)
    return render(request, 'job/update_normal_job_post.html', {'form': form})


def delete_normal_job_post(request, pk):
    normal_job_post = get_object_or_404(NormalJobPost, pk=pk)
    if request.method == 'POST':
        normal_job_post.delete()
    return redirect('job:normal_job_list')


def show_hospital_jobs(request):
    hospital_jobs = NormalJobPost.objects.filter(job_category='HS')
    return render(request, 'job/hospital_jobs.html', {'hospital_jobs': hospital_jobs})




def show_carousel_slider(request):
    sliders = CarouselSlider.objects.all()
    context = {
        'sliders':sliders
    }
    return render(request, "job/carousel_sliders.html", context)


class CarouselSliderCreateView(CreateView):
    form_class = AddSliderForm
    model = CarouselSlider
    template_name = "job/add_sliders.html"
    success_url = reverse_lazy('job:sliders')


class CarouselSliderUpdate(UpdateView):
    model = CarouselSlider
    form_class = CarouselSliderForm
    template_name = 'job/update_carousel.html'
    success_url = reverse_lazy('job:sliders')

class CarouselSliderDelete(DeleteView):
    model = CarouselSlider
    # template_name = 'yourapp/carouselslider_confirm_delete.html'
    success_url = reverse_lazy('job:sliders')



class ClientAdPhotosList(ListView):
    model = ClientAdPhotos
    template_name = 'job/clientadphotos_list.html'
    context_object_name = 'ad_photos'


class ClientAdPhotosCreate(CreateView):
    model = ClientAdPhotos
    form_class = ClientAdPhotosForm
    template_name = 'job/clientadphotos_form.html'
    success_url = reverse_lazy('job:ad_photo_list')


class ClientAdPhotosUpdate(UpdateView):
    model = ClientAdPhotos
    form_class = ClientAdPhotosForm
    template_name = 'job/clientadphotos_form.html'
    success_url = reverse_lazy('job:ad_photo_list')

class ClientAdPhotosDelete(DeleteView):
    model = ClientAdPhotos
    template_name = 'job/clientadphotos_confirm_delete.html'
    success_url = reverse_lazy('job:ad_photo_list')


class TermsAndConditionsListView(ListView):
    model = Terms_and_conditions
    template_name = 'job/terms_and_conditions.html'
    context_object_name = 'terms_and_conditions'



class TermsAndConditionsCreateView(CreateView):
    model = Terms_and_conditions
    template_name = 'terms_and_conditions_form.html'
    fields = ['matter']

    def get_success_url(self):
        return reverse('terms_and_conditions_list')

class TermsAndConditionsUpdateView(UpdateView):
    model = Terms_and_conditions
    template_name = 'terms_and_conditions_form.html'
    fields = ['matter']

    def get_success_url(self):
        return reverse('terms_and_conditions_list')

class TermsAndConditionsDeleteView(DeleteView):
    model = Terms_and_conditions
    template_name = 'terms_and_conditions_confirm_delete.html'

    def get_success_url(self):
        return reverse('terms_and_conditions_list')
    


def privacy_policy(request):
    return render(request, "job/workzen_privacy_policy.html")

job/templates/job/add_sliders.html
{% extends "job/base.html" %}

{% block page_heading %}
Add Sliders
{% endblock page_heading %}

{% block page_content %}
<div class="card py-4 px-4">
<div class="col-lg-6 col-md-6">
      <form action="" method="post" enctype="multipart/form-data" class="">
    {% csrf_token %}
    {% for fm in form %}
        <div class="form-group mb-3">
        {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.error|striptags}}</small>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
        {% if form.non_field_erros %}
            {% for error in form.non_field_erros %}
            <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %}
        {% endif %}
      </form>
    </div>
  </div>


{% endblock page_content %}

job/templates/job/carousel_sliders.html
{% extends "job/base.html" %}

{% block page_heading %}
Carousel Photos
{% endblock page_heading %}

{% block page_button %}
<a href="{% url "job:add_sliders" %}"><button type="button" class="btn btn-primary"><i class="bi bi-plus"></i></i> Add Slider</button></a>
{% endblock page_button %}


{% block page_content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Slider Name</th>
      <th scope="col">Thumbnail</th>
      <th scope="col">Thumbnail</th>
      <th scope="col">Thumbnail</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for slider in sliders %}
    <tr>
      <th scope="row">{{ slider.id }}</th>
      <td>{{ slider.created_at|date:"d-m-Y" }}</td>
      <td><a href="#">{{ slider.name }}</a></td>
      <td><img src="{{ slider.image1.url }}" style="width:120px; height:50px;" alt="{{job.post_name}}"></td>
      <td><img src="{{ slider.image2.url }}" style="width:120px; height:50px;" alt="{{job.post_name}}"></td>
      <td><img src="{{ slider.image3.url }}" style="width:120px; height:50px;" alt="{{job.post_name}}"></td>
      <td>
        <a href="{% url 'job:slider_update' slider.pk %}" class="btn btn-warning btn-sm mb-2">Edit</a>
        <form action="{% url "job:slider_delete" slider.pk %}" method="post" >
            {% csrf_token %}
              <input type="submit"
                class="btn btn-danger btn-sm" value="Delete">
             
          </form>
      </td>
    {% endfor %}
    </tr>
    
      
  </tbody>
</table>
{% endblock page_content %}

job/templates/job/client_interview_posts.html
{% extends "job/base.html" %}

{% block page_heading %}

Client Interview Jobs
{% endblock page_heading %}

{% block page_button %}
<a href="{% url "job:create_videsh_job" %}"><button type="button" class="btn btn-primary"><i class="bi bi-plus"></i></i> Add Job</button></a>
{% endblock page_button %}

{% block page_content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Thumbnail</th>
      <th scope="col">Job Name</th>
      {% comment %} <th scope="col">Job Category</th> {% endcomment %}
      <th scope="col">Mobile Number</th>
      <th scope="col">City</th>
      <th scope="col">Approved Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for job in job_posts %}
    <tr>
      <th scope="row">{{ job.id }}</th>
      <td>{{ job.created_at|date:"d-m-Y" }}</td>
      <td><img src="{{ job.post_image.url }}" style="width:50px; height:50px;" alt="{{job.post_name}}"></td>
      <td><a href="#">{{ job.post_name }}</a></td>
      {% comment %} <td>{{ job.job_category }}</td> {% endcomment %}
      <td>{{ job.mobile_phone1 }}</td>
      <td>{{ job.city }}</td>
      {% if job.is_approved %}
      <td class="text-center">&#10004;</td>
    {% else %}
    <td class="text-center">&#10008;</td>
    {% endif %}
      <td>
        <a href="{% url 'job:update_videsh_job_post' job.pk %}" class="btn btn-warning btn-sm mb-2">Edit</a>
        <form action="{% url 'job:delete_videsh_job_post' job.pk %}" method="post" >
          {% csrf_token %}
          <input type="submit" class="btn btn-danger btn-sm" value="Delete">
        </form>
      </td>
      
      {% endfor %}
    </tr>
    
      
  </tbody>
</table>
{% endblock page_content %}

job/templates/job/create_videsh_job_post.html
{% extends "job/base.html" %}

{% block page_heading %}
Create A New Videsh Job Post
{% endblock page_heading %}

{% block page_content %}
<div class="card py-4 px-4">
<div class="col-lg-6 col-md-6">
      <form action="" method="post" enctype="multipart/form-data" class="">
    {% csrf_token %}
    {% for fm in form %}
        <div class="form-group mb-3">
        {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.error|striptags}}</small>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Submit</button>
        {% if form.non_field_erros %}
            {% for error in form.non_field_erros %}
            <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %}
        {% endif %}
      </form>
    </div>
  </div>


{% endblock page_content %}

job/templates/job/desh_job.html
{% extends "job/base.html" %}

{% block page_heading %}

Desh me Job
{% endblock page_heading %}

{% block page_button %}
<a href="{% url "job:create_job_post" %}"><button type="button" class="btn btn-primary"><i class="bi bi-plus"></i></i> Add Job</button></a>
{% endblock page_button %}

{% block page_content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Date</th>
      <th scope="col">Thumbnail</th>
      <th scope="col">Job Name</th>
      <th scope="col">Job Category</th>
      <th scope="col">Mobile Number</th>
      <th scope="col">City</th>
      <th scope="col">Approved Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for job in job_lists %}
    <tr>
      <th scope="row">{{ job.id }}</th>
      <td>{{ job.created_at|date:"d-m-Y" }}</td>
      <td><img src="{{ job.post_image.url }}" style="width:50px; height:50px;" alt="{{job.post_name}}"></td>
      <td><a href="#">{{ job.post_name }}</a></td>
      <td>{{ job.job_category }}</td>
      <td>{{ job.mobile_phone1 }}</td>
      <td>{{ job.city }}</td>
      {% if job.is_approved %}
      <td class="text-center">&#10004;</td>
    {% else %}
    <td class="text-center">&#10008;</td>
    {% endif %}
      <td>
        <a href="{% url 'job:update_normal_job_post' job.pk %}" class="btn btn-warning btn-sm mb-2">Edit</a>
        <form action="{% url "job:delete_normal_job_post" job.pk %}" method="post" >
          {% csrf_token %}
            <input type="submit"
              class="btn btn-danger btn-sm" value="Delete">
           
        </form>
      </td>
      
      {% endfor %}
    </tr>
    
      
  </tbody>
</table>
{% endblock page_content %}

job/templates/job/sidebar.html
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item {% if request.path == '/' %}active{% endif %}">
        <a class="nav-link collapsed" href="/">
          <i class="bi bi-speedometer"></i>
          <span>Dashboard</span>
        </a>
      </li><!-- End Dashboard Nav -->

      
      

      <li class="nav-heading">Pages</li>

      {% comment %} <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'job:approve-job-list'%}">
          <i class="bi bi-question-circle"></i>
          <span>Approved Job Post</span>
        </a>
      </li> {% endcomment %}

      
      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-toggle="collapse" data-bs-target="#components-nav" href="#">
          <i class="bi bi-airplane"></i>
          <span>विदेश में जॉब</span>
          <i class="bi bi-chevron-down ms-auto"></i>
      </a>
      <ul id="components-nav" class="nav-content collapse">
          <li class="nav-item">
              <a href="{% url 'job:client_interview' %}">
                  <i class="bi bi-circle"></i>
                  <span>Client Interview</span>
              </a>
          </li>
          <li class="nav-item">
              <a href="{% url 'job:cv_selection' %}">
                  <i class="bi bi-circle"></i>
                  <span>CV Selection</span>
              </a>
          </li>
          <li>
            <a href="{% url "job:telephonic_interview" %}">
              <i class="bi bi-circle"></i><span>Zoom/ Telephonic</span>
            </a>
          </li>
          <li>
            <a href="{% url "job:licence_holder" %}">
              <i class="bi bi-circle"></i><span>Licence Holder</span>
            </a>
          </li>
          <!-- Add other child links here -->
      </ul>
  </li>
      
      <li class="nav-item">
        
          <a class="nav-link collapsed" href="{% url 'job:normal_job_list' %}">
          <i class="bi bi-suitcase-lg"></i>
          <span>देश में जॉब </span>
        </a>
      </li><!-- End Profile Page Nav -->

      <li class="nav-item">
        
          <a class="nav-link collapsed" href="{% url 'job:show_hospital_jobs' %}">
          <i class="bi bi-hospital"></i>
          <span>हॉस्पिटल में जॉब</span>
        </a>
      </li>

      <li class="nav-heading">Ads</li>
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'job:sliders'%}">
          <i class="bi bi-file-slides"></i>
          <span>Carousel Sliders</span>
        </a>
      </li> 
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'job:ad_photo_list'%}">
          <i class="bi bi-badge-ad"></i>
          <span>Mobile Ads</span>
        </a>
      </li>
      
      
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'job:terms_and_conditions'%}">
          <i class="bi bi-card-text"></i>
          <span>Terms & Conditions</span>
        </a>
      </li> 

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url "job:logout" %}">
          <i class="bi bi-box-arrow-in-right"></i>
          <span>Logout</span>
        </a>
      </li><!-- End Login Page Nav -->

      

    </ul>

  </aside>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
        // Find all the child links
        var childLinks = document.querySelectorAll('.nav-content a');

        // Loop through each child link and check if it matches the current URL
        childLinks.forEach(function (link) {
            if (link.href === window.location.href) {
                // Add the 'active' class to the parent collapsible section
                var parentCollapsible = link.closest('.nav-content');
                parentCollapsible.classList.add('show');
            }
        });
    });
</script>

job/templates/job/terms_and_conditions.html
{% extends "job/base.html" %}

{% block page_heading %}
Terms & Conditions
{% endblock page_heading %}

{% block page_button %}
<a href="#"><button type="button" class="btn btn-primary"><i class="bi bi-plus"></i></i>Edit Terms</button></a>
{% endblock page_button %}


{% block page_content %}

<div class="card p-5">
    <p class="p-2">{% lorem 3 p random %}</p>
</div>

{% endblock page_content %}